#pragma once

#define MOTION_LEFT_KP 2e1
#define MOTION_LEFT_KD 2e-6
#define MOTION_LEFT_KI 1e-4


#define MOTION_RIGHT_KP 1.5e1
#define MOTION_RIGHT_KD 0
#define MOTION_RIGHT_KI 1.9e-5

#define MOTION_TRANSLATION_KP 5.01e0
#define MOTION_TRANSLATION_KD 3e4
#define MOTION_TRANSLATION_KI 3.0e0

#define MOTION_ROTATION_KP 1.2e1
#define MOTION_ROTATION_KD 1e4
#define MOTION_ROTATION_KI 1e-5

#define MOTION_POWER_BASE 0.015
#define MOTION_POWER_MAX  0.03
#define MOTION_STARTUP_DISTANCE 500

#define MOTION_JOYSTICK_ANGLE_OUTREACH 3
