#pragma once

#define MOTION_LEFT_KP 1e1
#define MOTION_LEFT_KD 0
#define MOTION_LEFT_KI 0

#define MOTION_RIGHT_KP 2e1
#define MOTION_RIGHT_KD 0
#define MOTION_RIGHT_KI 0

#define MOTION_TRANSLATION_KP 1e1
#define MOTION_TRANSLATION_KD 1e1
#define MOTION_TRANSLATION_KI 2e-6

#define MOTION_ROTATION_KP 1e1
#define MOTION_ROTATION_KD 0
#define MOTION_ROTATION_KI 0

#define MOTION_POWER_BASE 0.2
#define MOTION_POWER_MAX  0.5
